# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFxjUBmasMTlFfEsOKxPefMFv_4wiTRL
"""

def vote(age):
  if age >= 18:
    print("You are eligible to vote")
  else:
    print("You are not eligible to vote")

while True:
  try :
    age = int(input("Enter your age: "))
    vote(age)
    break
  except:
    print("Invalid input")