# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFxjUBmasMTlFfEsOKxPefMFv_4wiTRL
"""

def seperater(list1):
  even = []
  odd = []
  for i in list1:
    if i%2 == 0:
     even.append(i)
    else:
     odd.append(i)
  return even,odd


a = int(input("Enter the number of elements in the list: "))
list1 = []
for i in range(a):
  list1.append(int(input("Enter the element: ")))
print("You need this in seprate form like even odd say Yes Or NO: " )
a = input()
if a == "yes" :
  print(seperater(list1))
else:
  print(list1)