# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFxjUBmasMTlFfEsOKxPefMFv_4wiTRL
"""

file = open("sample.txt","r")
a = file.read()
print(a)
file.close()